### ISSUE TITLE
Doesn't work with object caching

### ISSUE THREAD

**Issue by viktorix** [danielbachhuber/one-time-login#19]
We use Redis for object caching and usermeta by default is a cached group. So when a token is generated and saved to the usermeta table it's not saved in Redis. When trying to login using the URL it returns an invalid token error because $tokens var is empty.

A quick fix is to stop caching the usermeta table. 

I was thinking maybe it's worth saving tokens somewhere else, to continue caching the usermeta group. Possibly using wp_cache_add if object caching is active and wp_cache_delete to delete it.

**Comment by danielbachhuber** [comment]
Hi @viktorix 

> We use Redis for object caching and usermeta by default is a cached group. So when a token is generated and saved to the usermeta table it's not saved in Redis. When trying to login using the URL it returns an invalid token error because $tokens var is empty.

This seems like it might be an issue with your object caching drop-in, not with this plugin. 

Are you sure your object cache is loaded when you're running the WP-CLI command?

**Comment by viktorix** [comment]
@danielbachhuber thanks for a quick reply.

We're using [object-cache.php](https://raw.githubusercontent.com/pantheon-systems/wp-redis/master/object-cache.php) that comes with the [Redis Cache plugin](https://wordpress.org/plugins/redis-cache/).

one-time-login.php is included as a must-use plugin, which loads after the drop-in plugins. So it should be working correctly unless there's an issue. 

When I flush Redis cache, the login URL will work since there's no cache. But once the cache is updated, the login URL no longer works.

**Comment by danielbachhuber** [comment]
@viktorix Huh. You are aware that the login URLs only work once, right?

**Comment by viktorix** [comment]
@danielbachhuber yes. Sorry, let me clarify. If Redis already has cache and I generate URL, it will show invalid token error. This is also when $tokens is empty at that time. If I flush Redis cache, the same URL will work.  

That makes me think it initially tries to get token from cached usermeta table in Redis, which has no tokens. When I flush cache, it gets token from usermeta and updates Redis cache. Hope that makes sense.

**Comment by danielbachhuber** [comment]
Ok. I just tested One Time Login locally with an object cache and it works as expected. One Time Login uses WordPress APIs (`get_user_meta()` / `update_user_meta()`), and doesn't interact directly with the object cache API.

This seems like a problem specific to your system that will be hard to debug without being able to reproduce.

**Comment by viktorix** [comment]
Thanks. I was able to narrow down the problem to WP-CLI executing `update_user_meta()`.

In my tests, not using WP-CLI, `update_user_meta()` works as expected and updates the cache too. However, anytime it is used with WP-CLI it updates the database but not the cache.

I can confirm this with 
```wp eval 'update_user_meta("2", "one_time_login_token", "tokenYYY");'```

It updates the database but not the cache. So I'll need to do more troubleshooting to see why this is happening.

Thanks for your time replying and testing it with Redis.

**Comment by danielbachhuber** [comment]
> It updates the database but not the cache. So I'll need to do more troubleshooting to see why this is happening.

Huh. I'd also try this out:

1. Make sure your object cache drop-in is being loaded by WP-CLI. One quick test is:

```bash
$ wp cache set foo bar
Success: Set object 'foo' in group 'default'.
$ wp cache get foo
bar
```

2. Make sure WP-CLI and web requests are writing to the same object cache. `WP_CACHE_KEY_SALT` is sometimes used to shard the data; maybe that's only defined for web requests?
