### ISSUE TITLE
update wordpress.org version

### ISSUE THREAD

**Issue by Spreeuw** [danielbachhuber/one-time-login#21]
Thanks for a great plugin! Wordpress states:

> This plugin hasn’t been tested with the latest 3 major releases of WordPress. It may no longer be maintained or supported and may have compatibility issues when used with more recent versions of WordPress.

As far as I can tell it works fine with the latest WordPress (5.4), can you verify this and push an update to wordpress.org stating compatibility? Thanks!
https://wordpress.org/plugins/one-time-login/

**Comment by danielbachhuber** [comment]
Hey @Spreeuw,

For sure! I've bumped the 'Tested Up To' value on WordPress.org and in this repo.
