### ISSUE TITLE
API endpoint

### ISSUE THREAD

**Issue by pfefferle** [danielbachhuber/one-time-login#24]
Now, that WordPress implemented application passwords für API requests, what do you think about adding an API endpoint, to generate "one time tokens"?

**Comment by danielbachhuber** [comment]
Thanks for the suggestion, @pfefferle!

Could you describe your use case with a bit more detail? An API endpoint would require authentication and authorization. I deliberately only implemented a WP-CLI command originally to touching the complexity of authentication/authorization.

**Comment by pfefferle** [comment]
> Could you describe your use case with a bit more detail?

Sure :) We are investigation different solutions to generate one time tokens for our hosting customers and the CLI is a bit complicated, because we have to always use an SSL tunnel to generate tokens. So I thought an API endpoint might be a feasible alternative.

> An API endpoint would require authentication and authorization.

That is why I mentioned the `application passwords`. In my mind the endpoint is as easy as the permission example in the spec: https://developer.wordpress.org/rest-api/extending-the-rest-api/routes-and-endpoints/#permissions-callback ?

**Comment by danielbachhuber** [comment]
> We are investigation different solutions to generate one time tokens for our hosting customers and the CLI is a bit complicated, because we have to always use an SSL tunnel to generate tokens. So I thought an API endpoint might be a feasible alternative.

Makes sense!

> That is why I mentioned the application passwords. In my mind the endpoint is as easy as the permission example in the spec:

Could you clarify how you'd generate the application passwords? Would you have a hardcoded application password that would work across all sites, or would you need to first generate the application password for the user?

**Comment by pfefferle** [comment]
> Could you clarify how you'd generate the application passwords? Would you have a hardcoded application password that would work across all sites, or would you need to first generate the application password for the user?

Sure, the idea was to generate an `application password` during the installation process and pass it to the WordPress installation. But the plugin should not care about that process at all, if it would provide an API endpoint, it can be accessed using username/password and/or username/"application password".

Maybe to hide the API endpoint behind a constant, to make the usage of that endpoint explicit!

**Comment by danielbachhuber** [comment]
Cool. I'm amenable to this enhancement. Want to put together a pull request with tests? The code can live in `one-time-login.php` in a pattern similar to the rest of the code.

**Comment by gdespoulain** [comment]
Hi!

Here it is:
https://github.com/danielbachhuber/one-time-login/pull/28

**Comment by pfefferle** [comment]
thanks @gdespoulain :)
