### ISSUE TITLE
restAPI: rest_forbidden 401

### ISSUE THREAD

**Issue by multimania** [danielbachhuber/one-time-login#35]
Hello, I tried to use the restAPI in your plugin.
And unfortunately I get a "401" "rest_forbidden" as an answer.

Can somebody help me with it?

**Comment by danielbachhuber** [comment]
Hey there,

Sorry you're having issues! The generic "401 rest_forbidden" error means your API token or other authentication credential isn't being passed correctly to the REST API. Unfortunately, helping you fix this is outside of the support we offer.
